# Generated by Django 5.0.2 on 2024-03-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, default='defaultprofile.png', null=True, upload_to='images'),
        ),
    ]
