# Generated by Django 5.0.2 on 2024-04-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_testimonial_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimony',
            new_name='review',
        ),
    ]
