# Generated by Django 5.0.2 on 2024-05-05 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_service_products_service_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='products',
        ),
        migrations.AddField(
            model_name='service',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
