# Generated by Django 5.0.2 on 2024-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_service_products_service_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='product_type',
        ),
        migrations.AddField(
            model_name='service',
            name='product_type',
            field=models.ManyToManyField(null=True, to='main.product'),
        ),
    ]
