# Generated by Django 5.0.2 on 2024-05-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_servicetype_alter_service_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='defaultprofile.png', null=True, upload_to='images'),
        ),
    ]
