# Generated by Django 5.0.2 on 2024-05-07 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_subscribers_remove_product_service_type_product_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
